import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { StatusTagihan, DendaMode } from '@prisma/client';
import { sendWhatsAppMessage } from '@/lib/fonnte';
import { formatDateIndonesian, formatRupiah } from '@/lib/utils';
import { generateMonthlyBills } from '@/lib/tagihan';

function getJakartaDateParts(date: Date = new Date()) {
  const formatter = new Intl.DateTimeFormat('en-CA', {
    timeZone: 'Asia/Jakarta',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  });
  // 'en-CA' outputs YYYY-MM-DD
  const formatted = formatter.format(date);
  const [year, month, day] = formatted.split('-').map(Number);
  return { year, month, day, dateStr: formatted };
}

function getDifferenceInDaysJakarta(targetDate: Date, referenceDate: Date = new Date()): number {
  const target = getJakartaDateParts(targetDate);
  const ref = getJakartaDateParts(referenceDate);

  const d1 = new Date(Date.UTC(target.year, target.month - 1, target.day));
  const d2 = new Date(Date.UTC(ref.year, ref.month - 1, ref.day));

  const diffMs = d1.getTime() - d2.getTime();
  return Math.round(diffMs / (1000 * 60 * 60 * 24));
}

export async function GET(req: NextRequest) {
  try {
    const authHeader = req.headers.get('authorization');
    const cronSecret = process.env.CRON_SECRET;

    // Fail closed authorization
    if (!cronSecret || authHeader !== `Bearer ${cronSecret}`) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const now = new Date();
    const jakartaToday = getJakartaDateParts(now);

    // 1. Generate monthly bills automatically on the 1st of every month (Asia/Jakarta timezone)
    let autoGeneratedBillsCount = 0;
    if (jakartaToday.day === 1) {
      const genResult = await generateMonthlyBills();
      autoGeneratedBillsCount = genResult.generatedCount;
    }

    // 2. Load dynamic system settings (denda_mode, denda_per_hari, batas_reminder_hari, wa_template)
    let settings = await prisma.pengaturan.findUnique({ where: { id: 'default' } });
    if (!settings) {
      settings = await prisma.pengaturan.create({
        data: {
          id: 'default',
          harga_default: 1500000,
          denda_per_hari: 50000,
          denda_mode: DendaMode.HARIAN,
          batas_reminder_hari: 3,
          wa_template: 'Halo Sdr/i {NAMA}, Tagihan sewa kamar {KAMAR} periode {PERIODE} sebesar {JUMLAH} akan jatuh tempo pada {JATUH_TEMPO}.',
        },
      });
    }

    const batasReminderHari = settings.batas_reminder_hari ?? 3;
    const dendaPerHari = Number(settings.denda_per_hari || 50000);
    const dendaMode = settings.denda_mode || DendaMode.HARIAN;

    // 3. Query all unpaid or overdue bills
    const unpaidBills = await prisma.tagihan.findMany({
      where: {
        status: { in: [StatusTagihan.BELUM_BAYAR, StatusTagihan.TERLAMBAT] },
      },
      include: {
        kontrak: {
          include: {
            kamar: { select: { nomor_kamar: true } },
            penghuni: { select: { nama: true, no_hp: true } },
          },
        },
      },
    });

    let sentCount = 0;
    let lateUpdatedCount = 0;

    for (const tagihan of unpaidBills) {
      const dueDate = new Date(tagihan.jatuh_tempo);
      // Difference in days between dueDate and today (in Asia/Jakarta):
      // diffInDays > 0 : future due date
      // diffInDays === 0 : due today
      // diffInDays < 0 : overdue
      const diffInDays = getDifferenceInDaysJakarta(dueDate, now);
      const isOverdue = diffInDays < 0;
      const daysOverdue = isOverdue ? Math.abs(diffInDays) : 0;

      // Calculate fine (denda) based on denda_mode
      let calculatedDenda = 0;
      if (isOverdue) {
        if (dendaMode === DendaMode.HARIAN) {
          calculatedDenda = dendaPerHari * daysOverdue;
        } else {
          // TETAP (flat rate applied once)
          calculatedDenda = dendaPerHari;
        }

        // Update tagihan status and denda in DB if changed
        if (tagihan.status !== StatusTagihan.TERLAMBAT || Number(tagihan.denda) !== calculatedDenda) {
          await prisma.tagihan.update({
            where: { id: tagihan.id },
            data: {
              status: StatusTagihan.TERLAMBAT,
              denda: calculatedDenda,
            },
          });
          lateUpdatedCount++;
        }
      }

      // 4. Reminder Window & 24h Anti-Spam Check
      // Only send reminder if: today >= jatuh_tempo - batas_reminder_hari (i.e. diffInDays <= batasReminderHari)
      const isWithinReminderWindow = diffInDays <= batasReminderHari;
      if (!isWithinReminderWindow) {
        continue;
      }

      // Check 24-hour cooldown
      if (tagihan.terakhir_diingatkan_at) {
        const lastRemindedTime = new Date(tagihan.terakhir_diingatkan_at).getTime();
        const hoursSinceLastReminder = (now.getTime() - lastRemindedTime) / (1000 * 60 * 60);
        if (hoursSinceLastReminder < 24) {
          continue; // Anti-spam: skip if reminded in the last 24 hours
        }
      }

      const effectiveDenda = isOverdue ? calculatedDenda : Number(tagihan.denda);
      const totalJumlah = Number(tagihan.jumlah) + effectiveDenda;
      const phone = tagihan.kontrak.penghuni.no_hp;
      const nama = tagihan.kontrak.penghuni.nama;
      const nomorKamar = tagihan.kontrak.kamar.nomor_kamar;

      // 5. Build dynamic message from Settings wa_template
      let template = settings.wa_template || 'Halo Sdr/i {NAMA}, Tagihan sewa kamar {KAMAR} periode {PERIODE} sebesar {JUMLAH} akan jatuh tempo pada {JATUH_TEMPO}.';

      let waMessage = template
        .replace(/{NAMA}/g, nama)
        .replace(/{KAMAR}/g, nomorKamar)
        .replace(/{PERIODE}/g, tagihan.periode)
        .replace(/{JUMLAH}/g, formatRupiah(totalJumlah))
        .replace(/{JATUH_TEMPO}/g, formatDateIndonesian(dueDate));

      if (isOverdue) {
        waMessage = `*[PERINGATAN KETERLAMBATAN - MYKOST]*\n\n${waMessage}\n\n*Status: Terlambat ${daysOverdue} hari* (Denda: ${formatRupiah(effectiveDenda)})\nTotal Tagihan: *${formatRupiah(totalJumlah)}*.\nMohon segera melakukan pembayaran via aplikasi MyKost.`;
      } else {
        waMessage = `*[PENGINGAT TAGIHAN SEWA - MYKOST]*\n\n${waMessage}\n\nMohon lakukan pembayaran tepat waktu via aplikasi MyKost.`;
      }

      const success = await sendWhatsAppMessage({
        target: phone,
        message: waMessage,
      });

      if (success) {
        // Record timestamp to enforce 24h anti-spam cooldown
        await prisma.tagihan.update({
          where: { id: tagihan.id },
          data: { terakhir_diingatkan_at: now },
        });
        sentCount++;
      }
    }

    return NextResponse.json({
      success: true,
      message: `Pekerjaan cron tagihan selesai. ${autoGeneratedBillsCount > 0 ? `Generate ${autoGeneratedBillsCount} tagihan baru. ` : ''}Denda mode ${dendaMode}. ${lateUpdatedCount} tagihan diperbarui keterlambatannya. ${sentCount} pesan reminder WA terkirim.`,
      autoGeneratedBillsCount,
      lateUpdatedCount,
      sentCount,
    });
  } catch (error: any) {
    console.error('Cron tagihan error:', error);
    return NextResponse.json({ error: error.message || 'Gagal menjalankan cron tagihan' }, { status: 500 });
  }
}
